---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: centos
    version: 6
# No supported/sane way to run Ansible inside a CentOS 5 Docker container;
#   - distribution: centos
#     version: 5
#     pkg_cmd: yum
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 12.04

before_install:
  - 'sudo docker run -it --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:rw cyverse/ansible-test:latest-${distribution}-${version} bash'

script:
  # Syntax check
  - sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --syntax-check

  # Running role with vars undefined should pass but make no changes
  - >
    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Undefined vars test: pass' && exit 0)
    || (echo 'Undefined vars test: fail' && exit 1)

  # Set options
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e 'sudoers_mailto=test@example.com sudoers_mail_always=true'"

  # Idempotence test
  - >
    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e 'sudoers_mailto=test@example.com sudoers_mail_always=true'
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test that configuration options were set
  - sudo docker exec test_dummy cat /etc/sudoers

  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
    && (echo 'mailto test: pass' && exit 0)
    || (echo 'mailto test: fail' && exit 1)

  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
    && (echo 'mail_always test: pass' && exit 0)
    || (echo 'mail_always test: fail' && exit 1)

  # Unset options
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e 'sudoers_mailto=false sudoers_mail_always=false'"

  # Idempotence test
  - >
    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e 'sudoers_mailto=false sudoers_mail_always=false'
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test that configuration options were unset
  - sudo docker exec test_dummy cat /etc/sudoers

  - >
    if (sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=.*")
    then (echo 'mailto absent test: fail' && exit 1)
    else (echo 'mailto absent test: pass' && exit 0)
    fi

  - >
    if (sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always")
    then (echo 'mail_always absent test: fail' && exit 1)
    else (echo 'mail_always absent test: pass' && exit 0)
    fi

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
