---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
    pkg_cmd: yum
  - distribution: centos
    version: 6
    pkg_cmd: yum
  - distribution: centos
    version: 5
    pkg_cmd: yum
  - distribution: ubuntu
    version: 16.04
    pkg_cmd: apt-get
  - distribution: ubuntu
    version: 14.04
    pkg_cmd: apt-get
  - distribution: ubuntu
    version: 12.04
    pkg_cmd: apt-get

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine'
  - 'sudo docker run --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:rw ${distribution}:${version} bash'

install:
  - 'sudo docker exec test_dummy ${pkg_mgr} install python-pip'

  # Install ansible
  - 'sudo docker exec test_dummy pip install ansible'

  # Check ansible version
  - 'sudo docker exec test_dummy ansible --version'

  # Create ansible.cfg with correct roles_path
  - sudo docker exec test_dummy printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - sudo docker exec test_dummy ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - "sudo docker exec test_dummy ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - >
    sudo docker exec test_dummy ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
    && (echo 'mailto test: pass' && exit 0)
    || (echo 'mailto test: fail' && exit 1)

  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
    && (echo 'mail_always test: pass' && exit 0)
    || (echo 'mail_always test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
