---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: centos
    version: 6
# No supported/sane way to run Ansible inside a CentOS 5 Docker container;
#   - distribution: centos
#     version: 5
#     pkg_cmd: yum
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 12.04

before_install:
  - 'sudo docker run -it --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:rw cyverse/ansible-test:latest-${distribution}-${version} bash'

script:
  # Syntax check
  - sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --syntax-check

  # Playbook run test
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local"

  # Idempotence test
  - >
    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test that configuration options actually applied
  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
    && (echo 'mailto test: pass' && exit 0)
    || (echo 'mailto test: fail' && exit 1)

  - >
    sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
    && (echo 'mail_always test: pass' && exit 0)
    || (echo 'mail_always test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
