---
# tasks file for ansible-control-sudoers
- name: set sudoers mailto address
  when:
    - sudoers_mailto is defined
    - sudoers_mailto|bool != false
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    regexp: "^Defaults mailto=.*$"
    line: "Defaults mailto={{ sudoers_mailto }}"
    state: present
    insertbefore: "^# Defaults.*$"

- name: un-set sudoers mailto address
  when:
    - sudoers_mailto is defined
    - sudoers_mailto|bool == false
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    regexp: "^Defaults mailto=.*$"
    state: absent

- name: set mail_always
  when:
    - sudoers_mail_always is defined
    - sudoers_mail_always|bool != false
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "Defaults mail_always"
    state: present
    insertafter: "^# Defaults.*$"

- name: unset mail_always
  when:
    - sudoers_mail_always is defined
    - sudoers_mail_always|bool == false
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "Defaults mail_always"
    state: absent
