---
# tasks file for ansible-control-sudoers
- name: un-set existing sudoers mailto address
  when:
    - sudoers_mailto is defined
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    regexp: "^Defaults mailto=.*$"
    state: absent

- name: set sudoers mailto address
  when:
    - sudoers_mailto is defined
    - sudoers_mailto != "false"
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "Defaults mailto={{ sudoers_mailto }}"
    state: present
    insertbefore: "^# Defaults.*$"

- name: unset mail_always
  when:
    - sudoers_mail_always is defined
    - sudoers_mail_always == "false"
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "Defaults mail_always"
    state: absent

- name: set mail_always
  when:
    - sudoers_mail_always is defined
    - sudoers_mail_always != "false"
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "Defaults mail_always"
    state: present
    insertafter: "^# Defaults.*$"
